## Intro to tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [3]:
# Create tensors with tf.constant()
scalar=tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [4]:
#Check the number of dimensions
scalar.ndim

0

In [5]:
#Create a vector
vector=tf.constant([1,4,5])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 5])>

In [6]:
vector.ndim

1

In [7]:
matrix=tf.constant([[10,7],
                  [12,45]],dtype=tf.float32)

In [8]:
matrix.ndim

2

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [12., 45.]], dtype=float32)>

In [10]:
matrix.shape

TensorShape([2, 2])

In [11]:
tensor=tf.constant([[[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]])

In [12]:
tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [13]:
tensor.ndim

3

Scalar is a single number
Vector is a number with direction
matrix is a 2 dim array of numbers
tensor is a n dimensional array of numbers basically its a collection of matrices

### with variable

In [14]:
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [15]:
changable_tensor[0]=8
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
changable_tensor[0].assign(8)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7])>

In [17]:
unchangable_tensor[0]=9

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

## creating random tensors

In [18]:
random_1=tf.random.Generator.from_seed(42)# set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
random_3=tf.random.Generator.from_seed(23)
random_3=random_3.uniform(shape=(3,2))
random_3
## Uniform probability

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.9925091 , 0.20401764],
       [0.26398885, 0.79402816],
       [0.71974635, 0.47845697]], dtype=float32)>

### shuffle your tensor

In [21]:
not_shuffled=tf.constant([[1,2],
                         [3,4],
                         [4,5]])

In [22]:
tf.random.set_seed(45)# global level seed
tf.random.shuffle(not_shuffled,seed=45)# op level seed
# both are equal we can get same tensors

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [23]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

# Numpy to Tensors

In [24]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(8,9))

<tf.Tensor: shape=(8, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Main diff is tensors can run on GPU for faster computing

In [26]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
A=tf.constant(numpy_A,shape=(2,6,2))# numpy to tensor
A

<tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])>

### getting info from tensors

In [28]:
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank_4_tensor.ndim,rank_4_tensor.shape,tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## Indexing Tensors

In [31]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
# Get the first ele from each dim from each index except for last one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_2_tensor=tf.constant([[10,7],
                          [4,6]])

In [34]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6])>

In [35]:
## Add extra dim
rank_3_tensor=rank_2_tensor[...,tf.newaxis]

In [36]:
rank_3_tensor.ndim

3

In [37]:
rank_4_tensor=rank_3_tensor[:,tf.newaxis,:,:]

In [38]:
rank_4_tensor

<tf.Tensor: shape=(2, 1, 2, 1), dtype=int32, numpy=
array([[[[10],
         [ 7]]],


       [[[ 4],
         [ 6]]]])>

In [39]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  6]]])>

In [40]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 4,  6]]])>

In [41]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 6]]])>

## manipulating tensors
### Matrix multiplication

In [42]:
tensor*tensor#element wise

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81]],

       [[100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]],

       [[400, 441, 484, 529, 576],
        [625, 676, 729, 784, 841]]])>

In [43]:
t1=tf.constant([[10,5],
               [3,67]])

In [44]:
t1@t1 # with '@' operator

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 115,  385],
       [ 231, 4504]])>

In [45]:
tf.linalg.matmul(t1,t1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 115,  385],
       [ 231, 4504]])>

### 1. inner dim must match
### 2. resultant tensor shape is outer dim 

In [46]:
tf.matmul(tf.transpose(t1),t1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 109,  251],
       [ 251, 4514]])>

### changing the dtype of tensor
#### runs faster of float16 


In [47]:
t1.dtype

tf.int32

In [48]:
tf.cast(t1,dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3., 67.]], dtype=float16)>

In [49]:
tf.abs(t1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 3, 67]])>

In [50]:
t2=tf.constant(np.random.randint(-100,100,size=50))
t2

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([-65,  46,  47,   5, -75, -70,   5, -75,   6, -27, -87, -95,  51,
        32,  -9, -23,   8,  16,  52,   9, -69, -30, -21,  53,  63,  47,
        83, -67,  26,  65,  38, -80, -26, -74,  61, -60,  94,  69,  20,
       -85, -77,  78, -10,  49,  48, -66,  13,   6, -42,  32])>

In [51]:
tf.abs(t2)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([65, 46, 47,  5, 75, 70,  5, 75,  6, 27, 87, 95, 51, 32,  9, 23,  8,
       16, 52,  9, 69, 30, 21, 53, 63, 47, 83, 67, 26, 65, 38, 80, 26, 74,
       61, 60, 94, 69, 20, 85, 77, 78, 10, 49, 48, 66, 13,  6, 42, 32])>

In [52]:
np.min(t2)

-95

In [53]:
tf.reduce_min(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=-95>

In [54]:
tf.reduce_max(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=94>

In [55]:
np.max(t2)

94

In [56]:
tf.reduce_sum(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=-111>

In [57]:
np.sum(t2)

-111

In [58]:
np.std(t2)## standard deviation

54.27275191106491

In [59]:
np.std(t2)**2# variance

2945.5316

In [60]:
import tensorflow_probability as tfp

In [61]:
tfp.stats.variance(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=2945>

In [62]:
tf.math.reduce_std(tf.cast(t2,dtype=tf.float32))## convert into float 32 or 16 

<tf.Tensor: shape=(), dtype=float32, numpy=54.27275>

In [63]:
tf.argmax(t2)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [64]:
t2[tf.argmax(t2)]

<tf.Tensor: shape=(), dtype=int32, numpy=94>

In [65]:
tf.reduce_max(t2)==t2[tf.argmax(t2)].numpy()

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [66]:
tf.argmin(t2)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [67]:
t2[tf.argmin(t2)]

<tf.Tensor: shape=(), dtype=int32, numpy=-95>

In [68]:
## squeezing a tensor 
# removing all the single dims

In [69]:
tf.random.set_seed(42)
t3=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,50])

In [70]:
t3

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [71]:
t3.shape

TensorShape([1, 1, 1, 50])

In [72]:
t3_squeezed=tf.squeeze(t3)

In [73]:
t3

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [74]:
t3_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## One hot Encoding

In [75]:
l=[0,1,2,3]
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [76]:
tf.square(t3)

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
          1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
          5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-01,
          1.7738823e-02, 3.0037400e-01, 3.3017528e-01, 8.0943036e-01,
          8.9561006e-05, 2.7168143e-01, 4.0264672e-01, 3.9731771e-02,
          5.3205711e-01, 2.9793534e-01, 1.1570342e-02, 4.5793110e-01,
          4.3596479e-01, 1.1353558e-01, 3.6170322e-01, 4.4363216e-02,
          7.2716069e-01, 1.9414751e-01, 8.9970458e-01, 5.6418572e-02,
          6.5900785e-01, 2.7703318e-01, 2.4434039e-01, 4.6711516e-02,
          7.1524179e-01, 7.6018190e-01, 9.5102049e-02, 4.7169948e-01,
          5.6472950e-02, 6.1109054e-01, 9.3535668e-01, 4.7199135e-03,
          6.3798469e-01, 4.3597910e-01, 3.4474665e-01, 2.7098738e-02,
          5.4479504e-01, 1.0274617e-01]]]], dtype=float32)>

In [ ]:
tf.math.sqrt(t3)

In [ ]:
tf.math.log(t3)

In [ ]:
#finding access to gpus
tf.config.list_physical_devices("GPU")

In [ ]:
Invidia-smi